# Generated by Django 4.2.15 on 2024-09-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FIN', 'Finalizada'), ('PEN', 'Pendiente'), ('VEN', 'Vencida'), ('TER_VEN', 'Terminada Vencida')], default='PEN', max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('assigned_to', models.CharField(max_length=13)),
            ],
        ),
    ]
