# Generated by Django 4.2.15 on 2024-09-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='assigned_to',
            field=models.CharField(max_length=255),
        ),
    ]
