# Generated by Django 4.2.15 on 2024-09-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_tarea_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='status',
            field=models.CharField(choices=[('finalizada', 'Finalizada'), ('pendiente', 'Pendiente'), ('vencida', 'Vencida'), ('terminada_vencida', 'Terminada Vencida')], default='pendiente', max_length=30),
        ),
    ]
